In [68]:
import pandas as pd
import numpy as np
import sys
import os
from dotenv import load_dotenv
import json
import mlflow
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.inspection import permutation_importance

In [2]:
pd.set_option("display.max_columns", 100)
load_dotenv()
data_path = os.getenv("DATA_PATH")
src_path = os.getenv("SRC_PATH")
transaction_path = os.path.join(data_path, r"raw/train_transaction.csv/train_transaction.csv")
identity_path = os.path.join(data_path, r"raw/train_identity.csv/train_identity.csv")
transaction_df = pd.read_csv(transaction_path)
identity_df = pd.read_csv(identity_path)
full_df = transaction_df.merge(identity_df, on="TransactionID", how="left")
full_df = full_df.sort_values("TransactionDT").reset_index(drop=True)

In [42]:
sys.path.append(src_path)
from features.engineering import create_d_features
from data.split import temporal_split
from model.preprocessor_pipe_evalueate import evaluate_model, create_pipeline

In [53]:
json_path = os.path.join(data_path, r"processed/split_info.json")
with open(json_path, "r") as f:
    split_info = json.load(f)
    
train_end = split_info.get("train_end")
val_end = split_info.get("validation_end")

train, val, test = temporal_split(full_df, train_end, val_end)

In [52]:
test

Empty DataFrame
Columns: [TransactionID, isFraud, TransactionDT, TransactionAmt, ProductCD, card1, card2, card3, card4, card5, card6, addr1, addr2, dist1, dist2, P_emaildomain, R_emaildomain, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, M1, M2, M3, M4, M5, M6, M7, M8, M9, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21, V22, V23, V24, V25, V26, V27, V28, V29, V30, V31, V32, V33, V34, V35, V36, V37, V38, V39, V40, V41, V42, V43, V44, V45, ...]
Index: []

[0 rows x 434 columns]

In [54]:
map_dfs = {"train": train, "val": val, "test": test}

In [55]:
d_features_dfs = {}
for name, sample_df in map_dfs.items():
    d_features_dfs[name] = create_d_features(sample_df)

In [9]:
print("Total features:", len(d_features_dfs["train"].columns))
print(d_features_dfs["train"].columns.tolist())

Total features: 37
['TransactionDT', 'TransactionAmt', 'ProductCD', 'P_emaildomain', 'R_emaildomain', 'card1', 'card2', 'card4', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'missing_count', 'missing_V_count', 'missing_D_count', 'missing_M_count', 'missing_C_count', 'missing_id_count', 'missing_card_count', 'missing_addr_count', 'missing_dist_count', 'transaction_day', 'transaction_hour', 'transaction_amt_log', 'amount_decimal', 'hour_sin', 'hour_cos', 'P_emaildomain_is_missing', 'P_emaildomain_provider', 'R_emaildomain_is_missing', 'R_emaildomain_provider', 'domain_math', 'is_unusual_email', 'card_product', 'email_product', 'card_addr']

In [27]:
categorical_cols = d_features_dfs["train"].select_dtypes(include='object').columns.tolist()

In [37]:
def categoricl_fraud_rate(df, column, min_count = 100):
    products_stats = (df.groupby(column)['isFraud'].agg(["mean", "count"]).rename(columns = {"mean": "fraud_rate"}))
    products_stats['fraud_rate'] = products_stats['fraud_rate'] * 100

    return products_stats[products_stats['count'] >= min_count].sort_values("fraud_rate", ascending=False)

In [56]:
X_train = d_features_dfs["train"]
X_val = d_features_dfs["val"]

y_train = train["isFraud"]
y_val = val["isFraud"]

pipe = create_pipeline(X_train)

pipe.fit(X_train, y_train)

metrics = evaluate_model(pipe, X_val, y_val)

In [61]:
metrics

{'pr_auc': 0.23076717327719434,
 'roc_auc': 0.8317765385769453,
 'precision': 0.11486058301647656,
 'recall': 0.7149901380670611,
 'f1': 0.19792519792519792}

In [60]:
preprocessor = pipe.named_steps['preprocessor']
model = pipe.named_steps['model']

feature_names = preprocessor.get_feature_names_out()
coefficients = model.coef_[0]

coef_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefficients,
    "abs_coefficient": np.abs(coefficients)
})

In [66]:
coef_df.shape
coef_df.sort_values("coefficient", ascending=False).head(30)

                          feature  coefficient  abs_coefficient
11431    cat__card_addr_15063_nan     7.722047         7.722047
27775   cat__card_addr_6457_325.0     6.539311         6.539311
20978   cat__card_addr_2939_204.0     6.399613         6.399613
15489  cat__card_addr_16927_203.0     6.357897         6.357897
3247   cat__card_addr_11233_325.0     6.248562         6.248562
23628   cat__card_addr_4347_269.0     6.233026         6.233026
26416   cat__card_addr_5853_181.0     6.219047         6.219047
29284   cat__card_addr_7207_441.0     6.175477         6.175477
24242   cat__card_addr_4693_308.0     6.138248         6.138248
33897   cat__card_addr_9375_420.0     6.097948         6.097948
34199   cat__card_addr_9499_325.0     6.094081         6.094081
6961   cat__card_addr_12958_123.0     6.012061         6.012061
11520   cat__card_addr_1508_325.0     5.957720         5.957720
31459   cat__card_addr_8187_337.0     5.946636         5.946636
21747   cat__card_addr_3342_433.0     5.946186         5.946186
19090   cat__card_addr_2034_325.0     5.928101         5.928101
9748   cat__card_addr_14259_315.0     5.913855         5.913855
5747   cat__card_addr_12473_299.0     5.900164         5.900164
21620   cat__card_addr_3278_418.0     5.794291         5.794291
31224   cat__card_addr_8109_418.0     5.793184         5.793184
18322  cat__card_addr_18249_485.0     5.783041         5.783041
10324  cat__card_addr_14509_251.0     5.737840         5.737840
5614   cat__card_addr_12422_272.0     5.736283         5.736283
33161   cat__card_addr_9002_272.0     5.705567         5.705567
24864   cat__card_addr_5033_476.0     5.699964         5.699964
30246   cat__card_addr_7669_269.0     5.680604         5.680604
8298   cat__card_addr_13552_315.0     5.642421         5.642421
17236  cat__card_addr_17739_512.0     5.634431         5.634431
30202   cat__card_addr_7664_204.0     5.598569         5.598569
33330   cat__card_addr_9069_325.0     5.564038         5.564038

In [71]:
result = permutation_importance(
    pipe, X_val, y_val, n_repeats=10, random_state=42, n_jobs=-1
)

In [74]:
importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance_Mean': result.importances_mean,
    'Importance_Std': result.importances_std
})

importance_df = importance_df.sort_values(by='Importance_Mean', ascending=False)

In [78]:
importance_df.head(20)

                     Feature  Importance_Mean  Importance_Std
2                  ProductCD         0.014170        0.000243
36                 card_addr         0.013769        0.000964
29    P_emaildomain_provider         0.013215        0.000293
31    R_emaildomain_provider         0.012997        0.000616
18          missing_id_count         0.012767        0.000351
14           missing_V_count         0.008367        0.000425
30  R_emaildomain_is_missing         0.007007        0.000425
35             email_product         0.006641        0.000546
8                      card6         0.006373        0.000479
24       transaction_amt_log         0.006051        0.000482
33          is_unusual_email         0.005840        0.000430
34              card_product         0.005307        0.000430
26                  hour_sin         0.002812        0.000550
20        missing_addr_count         0.002665        0.000196
3              P_emaildomain         0.002655        0.000188
25            amount_decimal         0.002396        0.000430
13             missing_count         0.002051        0.000271
15           missing_D_count         0.001995        0.000468
28  P_emaildomain_is_missing         0.001561        0.000328
23          transaction_hour         0.001221        0.000387